name: Laravel Test

on:
  pull_request:
    branches:
      - main
      - staging

# ensure that only single workflow using the same concurrency group will run at a time.
concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1']
        redis-version: [6]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: todo_test
        ports: 
          - 8889:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Setup PHP dependencies
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    
    - name: Setup Redis Server
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: ${{ matrix.redis-version }}

    - name: Git checkout To Target Branch
      uses: actions/checkout@v2

    - name: Copy .env
      run: cp .env.example .env

    - name: Install Dependencies Laravel
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    
    - name: Generate Laravel Key
      run: php artisan key:generate
    
    - name: Update Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    
    - name: Execute Migrations and Unit Tests
      run: |
        php artisan migrate
        php artisan db:seed
        php artisan test
      env:
        APP_ENV: testing
        DB_HOST: 127.0.0.1
        DB_CONNECTION: mysql
        DB_DATABASE: todo_test
        DB_PORT: 8889
        DB_USERNAME: root
        DB_PASSWORD: root
        CACHE_DRIVER: redis
        SESSION_DRIVER: redis
        REDIS_CLIENT: predis
        REDIS_HOST: 127.0.0.1
        REDIS_PASSWORD: null
        REDIS_PORT: 6379
        REDIS_DB: 0
        REDIS_CACHE_DB: 1
        REDIS_SESSION_DB: 2
        TELESCOPE_ENABLED: false




